### ISSUE TITLE
unable to load 

### ISSUE THREAD

**Issue by superman19872011** [MayhemStudios/MayhemRimsPack#1]
> ensure "MayhemRimsPack"
[           resources] Warning: Resource MayhemRimsPack does not support the current game (gta5).
[ citizen-server-impl] Couldn't start resource MayhemRimsPack.
not sure what's wrong exactly

**Comment by FrequencyRoleplay** [comment]
You need to open the FX manifest .  it needs to tell it that its  GTA5 file. 

Look at your other resource manifest and compare

**Comment by FrequencyRoleplay** [comment]
fx_version 'cerulean'
game 'gta5'

**Comment by MayhemStudios** [comment]
Sorry yes, I've updated it on my end, but i forgot to update the last version. It should be fixed now.

It's just one of the things you forget now and then. 😄
